apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flask-app-external-secret
  namespace: web-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: flask-app-secret
    template:
      engineVersion: v2
      data:
        MONGO_URI: "mongodb://flaskapp:{{ .mongo_app_pass }}@10.3.0.10:27017/flaskdb"
  data:
    - secretKey: mongo_app_pass
      remoteRef:
        key: mongo_app_pass
